// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hospital/internal/modules/db/ent/patient"
	"hospital/internal/modules/db/ent/predicate"
	"hospital/internal/modules/db/ent/treatment"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TreatmentUpdate is the builder for updating Treatment entities.
type TreatmentUpdate struct {
	config
	hooks    []Hook
	mutation *TreatmentMutation
}

// Where appends a list predicates to the TreatmentUpdate builder.
func (tu *TreatmentUpdate) Where(ps ...predicate.Treatment) *TreatmentUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTablets sets the "tablets" field.
func (tu *TreatmentUpdate) SetTablets(s string) *TreatmentUpdate {
	tu.mutation.SetTablets(s)
	return tu
}

// SetPsychologicalTreatment sets the "psychologicalTreatment" field.
func (tu *TreatmentUpdate) SetPsychologicalTreatment(s string) *TreatmentUpdate {
	tu.mutation.SetPsychologicalTreatment(s)
	return tu
}

// SetSurvey sets the "survey" field.
func (tu *TreatmentUpdate) SetSurvey(s string) *TreatmentUpdate {
	tu.mutation.SetSurvey(s)
	return tu
}

// AddCuredIDs adds the "cured" edge to the Patient entity by IDs.
func (tu *TreatmentUpdate) AddCuredIDs(ids ...int) *TreatmentUpdate {
	tu.mutation.AddCuredIDs(ids...)
	return tu
}

// AddCured adds the "cured" edges to the Patient entity.
func (tu *TreatmentUpdate) AddCured(p ...*Patient) *TreatmentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.AddCuredIDs(ids...)
}

// Mutation returns the TreatmentMutation object of the builder.
func (tu *TreatmentUpdate) Mutation() *TreatmentMutation {
	return tu.mutation
}

// ClearCured clears all "cured" edges to the Patient entity.
func (tu *TreatmentUpdate) ClearCured() *TreatmentUpdate {
	tu.mutation.ClearCured()
	return tu
}

// RemoveCuredIDs removes the "cured" edge to Patient entities by IDs.
func (tu *TreatmentUpdate) RemoveCuredIDs(ids ...int) *TreatmentUpdate {
	tu.mutation.RemoveCuredIDs(ids...)
	return tu
}

// RemoveCured removes "cured" edges to Patient entities.
func (tu *TreatmentUpdate) RemoveCured(p ...*Patient) *TreatmentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.RemoveCuredIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TreatmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, TreatmentMutation](ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TreatmentUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TreatmentUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TreatmentUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TreatmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(treatment.Table, treatment.Columns, sqlgraph.NewFieldSpec(treatment.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Tablets(); ok {
		_spec.SetField(treatment.FieldTablets, field.TypeString, value)
	}
	if value, ok := tu.mutation.PsychologicalTreatment(); ok {
		_spec.SetField(treatment.FieldPsychologicalTreatment, field.TypeString, value)
	}
	if value, ok := tu.mutation.Survey(); ok {
		_spec.SetField(treatment.FieldSurvey, field.TypeString, value)
	}
	if tu.mutation.CuredCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedCuredIDs(); len(nodes) > 0 && !tu.mutation.CuredCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.CuredIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{treatment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TreatmentUpdateOne is the builder for updating a single Treatment entity.
type TreatmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TreatmentMutation
}

// SetTablets sets the "tablets" field.
func (tuo *TreatmentUpdateOne) SetTablets(s string) *TreatmentUpdateOne {
	tuo.mutation.SetTablets(s)
	return tuo
}

// SetPsychologicalTreatment sets the "psychologicalTreatment" field.
func (tuo *TreatmentUpdateOne) SetPsychologicalTreatment(s string) *TreatmentUpdateOne {
	tuo.mutation.SetPsychologicalTreatment(s)
	return tuo
}

// SetSurvey sets the "survey" field.
func (tuo *TreatmentUpdateOne) SetSurvey(s string) *TreatmentUpdateOne {
	tuo.mutation.SetSurvey(s)
	return tuo
}

// AddCuredIDs adds the "cured" edge to the Patient entity by IDs.
func (tuo *TreatmentUpdateOne) AddCuredIDs(ids ...int) *TreatmentUpdateOne {
	tuo.mutation.AddCuredIDs(ids...)
	return tuo
}

// AddCured adds the "cured" edges to the Patient entity.
func (tuo *TreatmentUpdateOne) AddCured(p ...*Patient) *TreatmentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.AddCuredIDs(ids...)
}

// Mutation returns the TreatmentMutation object of the builder.
func (tuo *TreatmentUpdateOne) Mutation() *TreatmentMutation {
	return tuo.mutation
}

// ClearCured clears all "cured" edges to the Patient entity.
func (tuo *TreatmentUpdateOne) ClearCured() *TreatmentUpdateOne {
	tuo.mutation.ClearCured()
	return tuo
}

// RemoveCuredIDs removes the "cured" edge to Patient entities by IDs.
func (tuo *TreatmentUpdateOne) RemoveCuredIDs(ids ...int) *TreatmentUpdateOne {
	tuo.mutation.RemoveCuredIDs(ids...)
	return tuo
}

// RemoveCured removes "cured" edges to Patient entities.
func (tuo *TreatmentUpdateOne) RemoveCured(p ...*Patient) *TreatmentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.RemoveCuredIDs(ids...)
}

// Where appends a list predicates to the TreatmentUpdate builder.
func (tuo *TreatmentUpdateOne) Where(ps ...predicate.Treatment) *TreatmentUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TreatmentUpdateOne) Select(field string, fields ...string) *TreatmentUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Treatment entity.
func (tuo *TreatmentUpdateOne) Save(ctx context.Context) (*Treatment, error) {
	return withHooks[*Treatment, TreatmentMutation](ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TreatmentUpdateOne) SaveX(ctx context.Context) *Treatment {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TreatmentUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TreatmentUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TreatmentUpdateOne) sqlSave(ctx context.Context) (_node *Treatment, err error) {
	_spec := sqlgraph.NewUpdateSpec(treatment.Table, treatment.Columns, sqlgraph.NewFieldSpec(treatment.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Treatment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, treatment.FieldID)
		for _, f := range fields {
			if !treatment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != treatment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Tablets(); ok {
		_spec.SetField(treatment.FieldTablets, field.TypeString, value)
	}
	if value, ok := tuo.mutation.PsychologicalTreatment(); ok {
		_spec.SetField(treatment.FieldPsychologicalTreatment, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Survey(); ok {
		_spec.SetField(treatment.FieldSurvey, field.TypeString, value)
	}
	if tuo.mutation.CuredCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedCuredIDs(); len(nodes) > 0 && !tuo.mutation.CuredCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.CuredIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treatment.CuredTable,
			Columns: []string{treatment.CuredColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Treatment{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{treatment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
