// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hospital/internal/modules/db/ent/predicate"
	"hospital/internal/modules/db/ent/treatment"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TreatmentDelete is the builder for deleting a Treatment entity.
type TreatmentDelete struct {
	config
	hooks    []Hook
	mutation *TreatmentMutation
}

// Where appends a list predicates to the TreatmentDelete builder.
func (td *TreatmentDelete) Where(ps ...predicate.Treatment) *TreatmentDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TreatmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TreatmentMutation](ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TreatmentDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TreatmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(treatment.Table, sqlgraph.NewFieldSpec(treatment.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TreatmentDeleteOne is the builder for deleting a single Treatment entity.
type TreatmentDeleteOne struct {
	td *TreatmentDelete
}

// Where appends a list predicates to the TreatmentDelete builder.
func (tdo *TreatmentDeleteOne) Where(ps ...predicate.Treatment) *TreatmentDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TreatmentDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{treatment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TreatmentDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
