version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-hospital
    environment:
      POSTGRES_PASSWORD: postgres
      PG_PASSWORD: postgres
      POSTGRES_DB: hospital
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
    volumes:
      - ../../../postgress-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-slave:
    image: postgres:13
    container_name: postgres-slave
    environment:
      POSTGRES_PASSWORD: postgres
      PG_PASSWORD: postgres
      POSTGRES_DB: hospital
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../../../postgress-slave:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433


  hospital:
    build: .
    image: hospital:latest
    depends_on:
      - postgres
    container_name: hospital
    env_file:
      - .env
    restart: always

  hospital-2:
    build: .
    image: hospital:latest
    depends_on:
      - postgres
    container_name: hospital-2
    environment:
      API_PORT: 81
    env_file:
      - .env
    restart: always

  hospital-3:
    build: .
    image: hospital:latest
    depends_on:
      - postgres
    container_name: hospital-3
    environment:
      API_PORT: 82
    env_file:
      - .env
    restart: always

  hospital-mirror:
    build: .
    image: hospital:latest
    depends_on:
      - postgres-slave
    container_name: hospital-mirror
    environment:
      API_PORT: 83
      DB_CONN_STRING: 'host=postgres-slave port=5433 user=postgres dbname=hospital password=postgres sslmode=disable'
      DBPort: 5433
    env_file:
      - .env
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - hospital
      - pgadmin
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/api:/etc/nginx/html/api
      - ../../../nginx/data:/opt/data
      - ./Readme.md:/var/www/html/documentation/Readme.md
      - ../../static:/static
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: xanderfox21@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ../../../pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    platform: linux/amd64
