version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-hospital
    environment:
      POSTGRES_PASSWORD: postgres
      PG_PASSWORD: postgres
      POSTGRES_DB: hospital
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../../../postgress-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: xanderfox21@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
#    volumes:
#      - ../../../pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    platform: linux/amd64

  hospital:
    build: .
    image: hospital:latest
    depends_on:
      - postgres
    container_name: hospital
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    depends_on:
      - hospital
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/api:/etc/nginx/html/api
      - ../../../nginx/data:/opt/data
    restart: always
