// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// Treatment is the predicate function for treatment builders.
type Treatment func(*sql.Selector)
